server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carshop
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

liquibase:
  change-log: classpath:db.changelog-master.xml